spring.application.name=event-registration

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Eventsss_DB
spring.datasource.username=Whatsss
spring.datasource.password=Eventsss
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
